let clrOne = document.querySelector("#clr-1");
let clrTwo = document.querySelector("#clr-2");
let body = document.getElementById("backgroundClr");
let randomButton = document.getElementById("randomBtn");

function changeBackground() {
  body.style.background =
    "linear-gradient(to right, " + clrOne.value + ", " + clrTwo.value + ")";
}

//there is a event for to detect any time the input of the input element changes => INPUT
clrOne.addEventListener("input", changeBackground);
clrTwo.addEventListener("input", changeBackground);
randomButton.addEventListener("click", function () {
  const colors = [];
  for (let i = 0; i < 100; i++) {
    let randomColors = Math.floor(Math.random() * 16777215).toString(16);
    //Math.random() generates a random decimal number between 0 and 1
    //Math.floor() rounds down a number to the nearest integer => takes the random decimal number generated by Math.random() and converts it into a whole number
    //* 16777215 => random number multiplied by 16777215 which represents the total number of colors available in hexadecimal notation
    //.toString(16) => method converts the number to a string and the argument 16 specifies that the number should be converted to a hexadecimal string
    randomColors = randomColors.padStart(6, "0");
    //padStart() to ensure that the hexadecimal string is always six characters long
    colors.push("#" + randomColors);
  }
  body.style.background =
    "linear-gradient(to right, " + colors[0] + ", " + colors[1] + ")";
  clrOne.value = colors[0];
  clrTwo.value = colors[1];
});
